spring:
  rabbitmq:
    virtual-host: /
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
    #不要提交两次。如果代码里是手动提交这里就是manual；默认是auto。
    listener:
      simple:
        acknowledge-mode: manual
server:
  port: 8021
